export const productsData = [
    {
        id: 1,
        name: 'Farenh (Gris)',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/anteojos.jpg',
        imageAlt: "Anteojos de sol",
        price: '$70.000',
        brand: 'Gucci',
        min: 1,
        stock: 5,
        categoryId: "Hombre"
    },
    {
        id: 2,
        name: 'Opium (Gris)',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/anteojos4.jpg',
        imageAlt: "Anteojos de sol",
        price: '$70.000',
        brand: 'Louis Vuitton',
        min: 1,
        stock: 3,
        categoryId: "Mujer"
    },
    {
        id: 3,
        name: 'Kenneth cole',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/anteojos5.jpg',
        imageAlt: "Anteojos de sol",
        price: '$40.000',
        brand: 'Bluth',
        min: 1,
        stock: 7,
        categoryId: "Hombre"
    },
    {
        id: 4,
        name: 'Litirial',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/anteojos6.jpg',
        imageAlt: "Anteojos de sol",
        price: '$25.000',
        brand: 'Vision',
        min: 1,
        stock: 9,
        categoryId: "Hombre"
    },
    {
        id: 5,
        name: 'Aviator',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/aviator.jpg',
        imageAlt: "Anteojos de sol",
        price: '$65.000',
        brand: 'Dior',
        min: 1,
        stock: 3,
        categoryId: "Hombre"
    },
    {
        id: 6,
        name: 'Butterfly',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/rayban.jpg',
        imageAlt: "Anteojos de sol",
        price: '$22.000',
        brand: 'RayBan',
        min: 1,
        stock: 9,
        categoryId: "Hombre"
    },
    {
        id: 7,
        name: 'Carey',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/carey.jpg',
        imageAlt: "Anteojos de sol",
        price: '$10.000',
        brand: 'XL',
        min: 1,
        stock: 7,
        categoryId: "Mujer"
    },
    {
        id: 8,
        name: 'Berlin',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/berlin.jpg',
        imageAlt: "Anteojos de sol",
        price: '$7.0000',
        brand: 'Kevingston',
        min: 1,
        stock: 5,
        categoryId: "Hombre"
    },
    {
        id: 9,
        name: 'Cat',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/xl.jpg',
        imageAlt: "Anteojos de sol",
        price: '$8.500',
        brand: 'XL',
        min: 1,
        stock: 5,
        categoryId: "Mujer"
    },
    {
        id: 10,
        name: 'Harry',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/ray.jpg',
        imageAlt: "Anteojos de sol",
        price: '$15.000',
        brand: 'RayBan',
        min: 1,
        stock: 3,
        categoryId: "Hombre"
    },
    {
        id: 11,
        name: 'XL',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/xxl.jpg',
        imageAlt: "Anteojos de sol",
        price: '$12.000',
        brand: 'XL',
        min: 1,
        stock: 9,
        categoryId: "Mujer"
    },
    {
        id: 12,
        name: 'Kevin',
        href: '#',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,",
        imageSrc: '/img/kevingston.jpg',
        imageAlt: "Anteojos de sol",
        price: '$7.000',
        brand: 'Kevingston',
        min: 1,
        stock: 7,
        categoryId: "Hombre"
    },
]
